import crypto from "crypto";
import fs from "fs";
import path from "path";

// Gitignored build source: vue-cli-service copies it to dist/, and the
// deploy scripts copy that to the repo root, where it's the single
// committed copy actually served at /Konstantin_Khitrykh_CV.pdf.
const PDF_PATH = "public/Konstantin_Khitrykh_CV.pdf";
const VERSION_PATH = "src/model/CvVersion.ts";

// Source of truth for the CV content now lives in the sibling ResumeBuilder
// repo. This script no longer renders the PDF itself — it just copies the
// built PDF from there into this repo's build pipeline.
const SOURCE_PDF_PATH = path.resolve(
  __dirname,
  "../../../ResumeBuilder/resumes/base/Konstantin_Khitrykh_CV.pdf",
);

function writeCvVersion(): void {
  const hash = crypto
    .createHash("sha256")
    .update(fs.readFileSync(PDF_PATH))
    .digest("hex")
    .slice(0, 16);
  const content = `// Auto-generated by src/scripts/generatePdf.ts — do not edit by hand.
// Content hash of the generated CV PDF, used to cache-bust the resume link
// so browsers (especially mobile) don't serve a stale PDF after a redeploy.
export const CV_VERSION = "${hash}";
`;
  fs.writeFileSync(VERSION_PATH, content);
  console.log(`CV version written: ${hash}`);
}

function generate(): void {
  if (!fs.existsSync(SOURCE_PDF_PATH)) {
    throw new Error(
      `CV source PDF not found at ${SOURCE_PDF_PATH}. Build it in the ResumeBuilder repo first.`,
    );
  }

  fs.mkdirSync(path.dirname(PDF_PATH), { recursive: true });
  fs.copyFileSync(SOURCE_PDF_PATH, PDF_PATH);

  console.log(`CV PDF copied from ${SOURCE_PDF_PATH} to ${PDF_PATH}`);
  writeCvVersion();
}

try {
  generate();
} catch (err) {
  console.error("PDF copy failed:", err);
  process.exit(1);
}
