import crypto from "crypto";
import fs from "fs";
import resumeDataJson from "../data/resume.json";
import type { ResumeData } from "../model/ResumeData";
import { renderResumeHtml } from "./resumeTemplate";
import { renderHtmlToPdf } from "../../tools/resume-pdf-exporter";

// Gitignored build source: vue-cli-service copies it to dist/, and the
// deploy scripts copy that to the repo root, where it's the single
// committed copy actually served at /Konstantin_Khitrykh_CV.pdf.
const PDF_PATH = "public/Konstantin_Khitrykh_CV.pdf";
const VERSION_PATH = "src/model/CvVersion.ts";

function writeCvVersion(): void {
  const hash = crypto
    .createHash("sha256")
    .update(fs.readFileSync(PDF_PATH))
    .digest("hex")
    .slice(0, 16);
  const content = `// Auto-generated by src/scripts/generatePdf.ts — do not edit by hand.
// Content hash of the generated CV PDF, used to cache-bust the resume link
// so browsers (especially mobile) don't serve a stale PDF after a redeploy.
export const CV_VERSION = "${hash}";
`;
  fs.writeFileSync(VERSION_PATH, content);
  console.log(`CV version written: ${hash}`);
}

async function generate(): Promise<void> {
  const resumeData = resumeDataJson as ResumeData;
  const html = renderResumeHtml(resumeData);

  await renderHtmlToPdf({
    html,
    outputPath: PDF_PATH,
    pdf: {
      margin: { top: "12mm", right: "14mm", bottom: "12mm", left: "14mm" },
    },
  });

  console.log(`CV PDF generated: ${PDF_PATH}`);
  writeCvVersion();
}

generate().catch((err) => {
  console.error("PDF generation failed:", err);
  process.exit(1);
});
