// Auto-generated by src/scripts/generatePdf.ts — do not edit by hand.
// Content hash of the generated CV PDF, used to cache-bust the resume link
// so browsers (especially mobile) don't serve a stale PDF after a redeploy.
export const CV_VERSION = "37b53fbda8faa87d";
